quiz_management_system/quiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home" ),
    path('add_quiz/', views.add_quiz, name="add_quiz" ),
    path('quiz_test/<int:id>/', views.quiz_test, name="quiz_test" ),
    path('quiz_list/', views.quiz_list, name="quiz_list" ),
    path('result/', views.resutl_view, name="result" ),
]

quiz_management_system/quiz_management_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('accounts/', include('user_admin.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz_management_system/quiz/models.py
from django.db import models
from user_admin.models import User
# Create your models here.

class Department(models.Model):
    name = models.CharField(max_length=150)
    def __str__(self):
        return self.name

class Semester(models.Model):
    semester_name = models.CharField(max_length=150)
    semester_year = models.CharField(max_length=150)
    create_date = models.DateField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.semester_name

class Course(models.Model):
    course_name = models.CharField(max_length=150)
    course_description = models.CharField(max_length=150)
    department_name = models.ForeignKey(Department, on_delete=models.CASCADE)
    semester_name = models.ForeignKey(Semester, on_delete=models.CASCADE, null=True)
    create_date = models.DateField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.course_name


class Quiz(models.Model):
    course_name = models.ForeignKey(Course, on_delete=models.CASCADE)
    question = models.CharField(max_length=250)
    option_1 = models.CharField(max_length=100)
    option_2 = models.CharField(max_length=100)
    option_3 = models.CharField(max_length=100)
    option_4 = models.CharField(max_length=100)
    marks = models.IntegerField(default=1)
    answer = models.CharField(max_length=100, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.question


class Result(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course_name = models.ForeignKey(Course, on_delete=models.CASCADE)
    marks = models.IntegerField()
    exam_date = models.DateField(auto_now_add=True)
    comments = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.course_name.course_name

quiz_management_system/quiz/forms.py
from django import forms
from .models import *

class Quizform(forms.ModelForm):
    class Meta:
        model=Quiz
        fields="__all__"
        widgets = {
            'question': forms.TextInput(attrs={'class': 'form-control'}),
            'option_1': forms.TextInput(attrs={'class': 'form-control'}),
            'option_2': forms.TextInput(attrs={'class': 'form-control'}),
            'option_3': forms.TextInput(attrs={'class': 'form-control'}),
            'option_4': forms.TextInput(attrs={'class': 'form-control'}),
            'marks': forms.NumberInput(attrs={'class': 'form-control'}),
            'answer': forms.TextInput(attrs={'class': 'form-control'})
        }

quiz_management_system/quiz/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from .forms import Quizform
from .models import Quiz, Course, Semester, Result
from user_admin.models import User
from django.contrib import messages
from user_admin.models import User as UUser
# Create your views here.

@login_required
def home(request):
    context={}
    courses = Course.objects.filter(active=True)
    context['courses'] = courses
    l = Group.objects.all()
    return render(request, 'index.html', context)


@login_required
def quiz_list(request):
    context={}
    quizes = Quiz.objects.all()
    context['quizes'] = quizes
    return render(request, 'quiz/quiz_list.html', context)

@login_required
def quiz_test(request, id):
   context={}
   course = Course.objects.get(id=id)
   questions = Quiz.objects.filter(course_name=course)
   context['questions'] = questions
   context['course'] = course

   if request.POST:
       print(request.POST, "All Input Answer")
       # questions = Quiz.objects.all()
       # course = Course.objects.get(id=id)
       # questions = Quiz.objects.filter(course_name=course)
       total_marks = 0
       wrong_answer = 0
       correct_answer = 0
       total = 0
       for q in questions:
           total += 1
           print(request.POST.get(q.question), "Select option")
           print(q.answer, "Answer")
           print()
           if q.answer == request.POST.get(q.question):
               total_marks += q.marks
               correct_answer += 1
           else:
               wrong_answer += 1
       percent = (total_marks / total) * 100
       try:
           profile_user = request.user
           if profile_user == User.objects.get(email=profile_user):
               user = User.objects.get(email=profile_user)
               print(user, "UUUUUUUUUUUUUU")
               Result.objects.create(user=user, course_name=course, marks=total_marks, )
               context['marks'] = total_marks
               context['time'] = request.POST.get('timer')
               context['correct'] = correct_answer
               context['wrong'] = wrong_answer
               context['total'] = total
               context['percent'] = percent
               return render(request, 'quiz/instant_result.html', context)
       except Exception as err:
           messages.warning(request, f"{err}")
       # user = UserProfile.objects.get(user=profile_user)
       # Result.objects.create(user=user, course_name=course, marks=total_marks, )
       # context['marks'] = total_marks
       # context['time'] = request.POST.get('timer')
       # context['correct'] = correct_answer
       # context['wrong'] = wrong_answer
       # context['total'] = total
       # context['percent'] = percent
       # return render(request, 'quiz/instant_result.html', context)

   return render(request, 'quiz/quiz_test.html', context)




def add_quiz(request):
    context={}
    forms = Quizform()
    courses = Course.objects.filter(active=True)
    context['courses'] = courses
    if request.POST:
        forms = Quizform(request.POST)
        if forms.is_valid():
            forms.save()
            return redirect('quiz_list')
    context['forms']=forms
    return render(request, 'quiz/add_quiz.html', context)


def resutl_view(request):
    context={}
    user = request.user
    results = Result.objects.filter(user=user)
    context['results'] = results
    return render(request, 'quiz/result.html', context)


# def quiz_test_by_course(request, id):
#     course = Course.objects.get(id=id)
#     quizs = Quiz.objects.filter(course_name=course)
#     print(quizs, "Course wise quiz")
#
#     return redirect('home')

quiz_management_system/templates/quiz/add_quiz.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="content container-fluid">

    <div class="page-header">
        <div class="row">
            <div class="col-sm-12">
                <h3 class="page-title">Quiz Test</h3>
                <ul class="breadcrumb">
                    <li><a href="{% url 'home' %}">Dashboard / </a></li>
                    <li class="breadcrumb-item active"> Quiz Test</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2>Quiz Test</h2>
                </div>
                <div class="card-body">


                    <form method='post' action=''>
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="id_course_name" class="col-form-label col-md-2">Course name:</label>
                            <div class="col-md-10">
                            <select class="form-select" name="course_name" required="" id="id_course_name">
                                <option value="0" selected="">Course Name</option>
                                {% for course in courses %}
                                <option value="{{ course.id }}">{{ course.course_name }}</option>
                                {% endfor %}
                            </select>
                          </div>
                            </div>

                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Question:</label>
                            <div class="col-md-10">
                                {{ forms.question }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Option 1:</label>
                            <div class="col-md-10">
                                {{ forms.option_1 }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Option 2:</label>
                            <div class="col-md-10">
                                {{ forms.option_2 }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Option 3:</label>
                            <div class="col-md-10">
                                {{ forms.option_3 }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Option 4:</label>
                            <div class="col-md-10">
                                {{ forms.option_4 }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Marks:</label>
                            <div class="col-md-10">
                                {{ forms.marks }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Answer:</label>
                            <div class="col-md-10">
                                {{ forms.answer }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Active:</label>
                            <div class="col-md-10">
                                {{ forms.active }}
                            </div>
                        </div>

                        <br>
                        <button type="submit" class="btn btn-primary">Submit</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

quiz_management_system/templates/quiz/instant_result.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="content container-fluid">

    <div class="card-columns" style="padding: 10px; margin: 20px;">
        <div class="card" align="centre " style="width: 32rem;">
            <img class="card-img-top" src="https://www.ukrgate.com/eng/wp-content/uploads/2021/05/Announcing-the-Results-of-the-External-Examination-in-Mathematics-in-June-221.jpg" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Score: {{marks}}</h5>

                <p class="card-text">Percentage: {{percent}}%</p>
<!--                <p class="card-text">Time Taken: {{time}} seconds</p>-->
                <p class="card-text">Correct answers: {{correct}}</p>
                <p class="card-text">Incorrect answers: {{wrong}}</p>
                <p class="card-text">Total questions: {{total}}</p>
                <h5>All the best for next quiz!</h5>
            </div>
        </div>
    </div>
</div>
{% endblock %}

quiz_management_system/templates/quiz/quiz_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
        <div class="content container-fluid">

            <div class="page-header">
                <div class="row align-items-center">
                    <div class="col">
                        <h3 class="page-title">Quiz List</h3>
                        <ul class="breadcrumb">
                            <li><a href="{% url 'home' %}">Dashboard / </a>
                            </li>
                            <li class="breadcrumb-item active"> Quiz List</li>
                        </ul>
                    </div>
                    <div class="col-auto">
                        <a href="" class="btn btn-primary mr-1">
                            <i class="fas fa-plus"></i>
                        </a>
                        <a class="btn btn-primary filter-btn" href="javascript:void(0);" id="filter_search">
                            <i class="fas fa-filter"></i>
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show mb-0 mt-3" role="alert">
                        <strong>Success!</strong> {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div>
                </div>
            </div>


            <div id="filter_inputs" class="card filter-card">
                <div class="card-body pb-0">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <form method="GET">
                                <div class="form-group">
                                <input type="text" class="form-control" name="name" placeholder="Search here...">
                            </div>
                            </form>

                        </div>
<!--                        <div class="col-sm-6 col-md-3">-->
<!--                            <div class="form-group">-->
<!--                                <label>Name</label>-->
<!--                                <input type="text" class="form-control">-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="col-sm-6 col-md-3">-->
<!--                            <div class="form-group">-->
<!--                                <label>Email</label>-->
<!--                                <input type="text" class="form-control">-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="col-sm-6 col-md-3">-->
<!--                            <div class="form-group">-->
<!--                                <label>Phone</label>-->
<!--                                <input type="text" class="form-control">-->
<!--                            </div>-->
<!--                        </div>-->
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="card card-table">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-center table-hover">
                                    <thead class="thead-light">
                                    <tr>
                                        <th>Questions</th>
                                        <th>Answer</th>
                                        <th>Marks</th>
                                        <th>Active</th>
                                        <th class="text-right">Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for quiz in quizes %}
                                    <tr>
                                        <td>
                                            <h2 class="table-avatar">
                                                {{ quiz.question }}
                                            </h2>
                                        </td>
                                        <td>
                                            <h2>{{ quiz.answer }}</h2>
                                        </td>
                                        <td>
                                            <h2>{{ quiz.marks }}</h2>
                                        </td>
                                        <td>
                                            {{ quiz.active }}
                                        </td>
                                        <td class="text-right">
                                            <a href="/dashboard/edit-employee/{{ employee.id }}" class="btn btn-sm btn-white text-success mr-2"><i
                                                    class="far fa-edit mr-1"></i> Edit</a>
                                            <a href="" class="btn btn-sm btn-white text-danger mr-2" data-toggle="modal" data-target="#exampleModal"
                                            onclick="show_modal({{ employee.id }})"><i
                                                    class="far fa-trash-alt mr-1"></i>Delete</a>
<!--
                                            <a href="javascript:void(0);" class="btn btn-sm btn-white text-danger mr-2"><i
                                                    class="far fa-trash-alt mr-1"></i>Delete</a>
-->
                                        </td>
                                    </tr>
                                    {% endfor %}
            <div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade" id="exampleModal"
                 role="dialog"
                 tabindex="-1">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Warning!!!!</h5>
                            <button aria-label="Close" class="close" data-dismiss="modal"
                                    type="button">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure to delete this employee.</p>
                        </div>
                        <div class="modal-footer">
                            <form action="/dashboard/inactive-employee" method="get">
                                <input class="form-control" id="modal_employee_id"
                                       name="deleted_employee_id" type="hidden">
                                <button class="btn btn-secondary" data-dismiss="modal"
                                        type="button">No
                                </button>
                                <button class="btn btn-primary" type="submit"><i
                                        class="far fa-trash-alt mr-1"></i>Yes
                                </button>
                                <!--                    <button  onclick="del_product({{product.id}})"  type="button" class="btn btn-primary" data-dismiss="modal">Delete</button>-->
                            </form>
                        </div>
                    </div>
                </div>
            </div>


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<script>
        function show_modal(employee_id){
        document.getElementById('modal_employee_id').value = employee_id

        }
</script>
{% endblock %}

quiz_management_system/templates/quiz/quiz_test.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="content container-fluid">

    <div class="page-header">
        <div class="row">
            <div class="col-sm-12">
                <h3 class="page-title">Quiz Test</h3>
                <ul class="breadcrumb">
                    <li><a href="{% url 'home' %}">Dashboard / </a></li>
                    <li class="breadcrumb-item active">Quiz Test</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                <div class="row">
                   <div class="col-lg-12">
                       {% if messages %}
                        <div class="messages">
                        {% for message in messages %}
                            <div class="alert{% if message.tags %} {{ message.tags }} {% endif %}" role="alert">{{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                        </div>
                        {% endif %}
                   </div>
               </div>
                    <h2 class="text-center my-3 pb-5">Computer Science & Engineering Quiz Test</h2>
                    <h3 class="text-center my-3 pb-5">Course name: {{ course.course_name }}</h3>

<!--                    <div align="right " id="displaytimer"><b>Timer: 0 seconds</b></div>-->

                    <form method='post' action='' class="mx-5">
                        {% csrf_token %}
                        {% for q in questions%}
                        <div class="form-group">
                            <label for="question">{{q.question}}</label>
                        </div>
                        <div class="form-check">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{q.question}}" id="gridRadios1"
                                       value="{{q.option_1}}">
                                <label class="form-check-label" for="gridRadios1">
                                    {{q.option_1}}
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{q.question}}" id="gridRadios2"
                                       value="{{q.option_2}}">
                                <label class="form-check-label" for="gridRadios2">
                                    {{q.option_2}}
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{q.question}}" id="gridRadios3"
                                       value="{{q.option_3}}">
                                <label class="form-check-label" for="gridRadios3">
                                    {{q.option_3}}
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{q.question}}" id="gridRadios4"
                                       value="{{q.option_4}}">
                                <label class="form-check-label" for="gridRadios4">
                                    {{q.option_4}}
                                </label>
                            </div>
                            <br>
                            <p>{{q.answer}} </p>
                        </div>
                        {% endfor %}
                        <br>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}